version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0
  # Configuration for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
