name: Build the images
on:
  workflow_dispatch:
    inputs:
      version:
        description: LilyPond version
        required: true
      tag:
        description: Image tag ("stable" or "devel")
        required: true
        default: devel
      latest:
        description: Latest
        required: true
        default: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build (latest)
        id: docker_build_latest
        uses: docker/build-push-action@v5
        if: github.event.inputs.latest == 'true'
        with:
          push: false
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
          tags: |
            ${{ github.repository_owner }}/lilypond:latest
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.tag }}
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (latest)
        if: github.event.inputs.latest == 'true'
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        if: github.event.inputs.latest != 'true'
        with:
          push: false
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
          tags: |
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.tag }}
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest
        if: github.event.inputs.latest != 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build (fonts)
        id: docker_build_fonts
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-fonts
          tags: |
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.tag }}-fonts
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.version }}-fonts
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (fonts)
        run: echo ${{ steps.docker_build_fonts.outputs.digest }}
      - name: Build (ly2video)
        id: docker_build_ly2video
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-ly2video
          tags: |
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.tag}}-ly2video
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.version }}-ly2video
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (ly2video)
        run: echo ${{ steps.docker_build_ly2video.outputs.digest }}
      - name: Build (fonts & ly2video)
        id: docker_build_fonts_ly2video
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-fonts-ly2video
          tags: |
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.tag}}-fonts-ly2video
            ${{ github.repository_owner }}/lilypond:${{ github.event.inputs.version }}-fonts-ly2video
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (fonts & ly2video)
        run: echo ${{ steps.docker_build_ly2video.outputs.digest }}
