name: Build and push the images to DockerHub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LilyPond version'
        required: true
      tag:
        description: 'Image tag ("stable" or "devel")'
        required: true
        default: 'devel'
      latest:
        description: 'Latest'
        required: true
        default: 'true'
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push (latest)
        id: docker_build_latest
        uses: docker/build-push-action@v3
        if: github.event.inputs.latest == 'true'
        with:
          push: true
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
          tags: |
            jeandeaual/lilypond:latest
            jeandeaual/lilypond:${{ github.event.inputs.tag }}
            jeandeaual/lilypond:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (latest)
        if: github.event.inputs.latest == 'true'
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        if: github.event.inputs.latest != 'true'
        with:
          push: true
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
          tags: |
            jeandeaual/lilypond:${{ github.event.inputs.tag }}
            jeandeaual/lilypond:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest
        if: github.event.inputs.latest != 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build and push (fonts)
        id: docker_build_fonts
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-fonts
          tags: |
            jeandeaual/lilypond:${{ github.event.inputs.tag }}-fonts
            jeandeaual/lilypond:${{ github.event.inputs.version }}-fonts
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (fonts)
        run: echo ${{ steps.docker_build_fonts.outputs.digest }}
      - name: Build and push (ly2video)
        id: docker_build_ly2video
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-ly2video
          tags: |
            jeandeaual/lilypond:${{ github.event.inputs.tag}}-ly2video
            jeandeaual/lilypond:${{ github.event.inputs.version }}-ly2video
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (ly2video)
        run: echo ${{ steps.docker_build_ly2video.outputs.digest }}
      - name: Build and push (fonts & ly2video)
        id: docker_build_fonts_ly2video
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            LILYPOND_VERSION=${{ github.event.inputs.version }}
            SUFFIX=-fonts-ly2video
          tags: |
            jeandeaual/lilypond:${{ github.event.inputs.tag}}-fonts-ly2video
            jeandeaual/lilypond:${{ github.event.inputs.version }}-fonts-ly2video
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
      - name: Image digest (fonts & ly2video)
        run: echo ${{ steps.docker_build_ly2video.outputs.digest }}
