name: Update DockerHub description
on:
  push:
    branches:
      - master
    paths:
      - 'README.md'
jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Update DockerHub repository description
        uses: peter-evans/dockerhub-description@v2
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          description: jeandeaual/lilypond
